### ISSUE TITLE
Change text "nugget size"

### ISSUE THREAD

**Issue by ShamanTcler** [intel/openvino-plugins-ai-audacity#119]
Took me a while to get this plug-in working on Win 11, but it works now   😁 (version 3.4.2, on Win 11 x64 insiders build)
    - needed dlls from https://github.com/BtbN/FFmpeg-Builds/   used ffmpeg-n6.0-162-g07e3223dd0-win64-gpl-shared-6.0.zip to get avformat-60.dll   ... dropped it into the audacity folder
    - putting thing into the openvino-models folder caught me too
    

Anyway, all is good now... 

When your plug-in transcribes it seems like it is trying to create "sentence nuggets". Is it possible to do "word nuggets"?

Tools like _descript_ show the word transcription over top the wave form allowing somewhat precise snipping to remove a snippet of sound.

In a similar vein filler words like uhm and ah .... are those detected? If so, removing those automagically might be possible.

**Comment by RyanMetcalfeInt8** [comment]
Hi @ShamanTcler,

Glad you were able to get things working!

> - needed dlls from https://github.com/BtbN/FFmpeg-Builds/ used ffmpeg-n6.0-162-g07e3223dd0-win64-gpl-shared-6.0.zip to get avformat-60.dll ... dropped it into the audacity folder

Hmm, I suppose you were looking at those avformat DLL errors in the log, and thought it was due to OpenVINO? This is actually something printed by Audacity itself, and would have printed even if you didn't have our OpenVINO module present. :smile:

> When your plug-in transcribes it seems like it is trying to create "sentence nuggets". Is it possible to do "word nuggets"?

We have a big update releasing this week to coincide with Audacity's 3.5.0 release. In there, you'll find more options for transcription, including the ability to set the 'Max Segment Length'. Setting this to '1' should produce 'word level' transcripts -- aka "nuggets" :smile:

See updated documentation here: https://github.com/intel/openvino-plugins-ai-audacity/tree/main/doc/feature_doc/whisper_transcription

I haven't spent too much time playing around with this feature myself, but I do want to point out that timestamps for individual words *may not* be super accurate (unfortunately). 

Thanks,
Ryan

**Comment by ShamanTcler** [comment]
Well, I just played with "ah", "um" and "heavy breathing" .... Ah became Oh  .... Um became um, finally ...  heavy breathing was just ignored.

Using word level discretization, export to a word processor .... let the grammar checker have at it. A few greps and awks latter, and you have a rough map to clean up the audio.

The ability to mark silent (below a threshold) sections with a text string could be interesting.

Let me explain my use case. I am creating videos on how to use a 3 Axis CNC machine (Onefinity Elite Foreman). I use FreeCad (Open Source Cad)  .... I first record voice using Audacity ( Open Source Audio)  then it goes to KdenLive (Open Source Video/Audio)... finally posted to YouTube.   I am a real amateur but getting better, working on video #2 now.

I am retired, and this work is only to help the CNC community... but hey if YouTube revenue buys me a toolbit who am I to complain.

**Comment by RyanMetcalfeInt8** [comment]
Hi @ShamanTcler,

We've posted the updated release here: https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.0-R2

And thanks for the feedback -- we've heard many others request this 'remove audible pause' feature, so our team will think about how it could be made possible in this project. 

I'll close this issue for now, but feel free to keep commenting, or feel free to contribute to some current discussion, including this one: https://github.com/intel/openvino-plugins-ai-audacity/discussions/121

Thanks!
