### ISSUE TITLE
Music Generation Super Slow!, The Remaining time will say it will take an hour.

### ISSUE THREAD

**Issue by SplendidPiePizza** [intel/openvino-plugins-ai-audacity#158]
Does this happen to cpu? why does it take forever to load Music Generation. I don't believe the remaining time, can anyone know why does this happen?

**Comment by RyanMetcalfeInt8** [comment]
Hi @SplendidPiePizza,

For non-CPU devices such as GPU, during the load operation, OpenVINO needs to perform a bunch of OpenCL compilations to produce the executable code that will run on the GPU. Note that this only happens the very first time that the feature is run, and the executable (or blob) is cached on disk to speed up the process for the next time.

This is why the load operation can be take a long time (usually a few minutes or so), especially for large models like MusicGen. And note that during this compilation phase, there is no way for our plugins to receive any progress reports from the OpenVINO framework -- which is why there are no updates to the Audacity progress dialog (and so 'remaining time' calculations, etc. will not be accurate).
