### ISSUE TITLE
v3.5.1-R2.2- Music Separation on GPU Quadro P2200 (GPU.1) fails and Music Style Remix n0t showing as an effect 

### ISSUE THREAD

**Issue by umishrak** [intel/openvino-plugins-ai-audacity#227]
I did download this version yesterday with the installer. I tried all three Separation Modes, i.e.: CPU, GPU.0 (integrated UHD Graphics 630), and GPU.1 (Nvidia Quadro P 2200) for the Music Separation Effect. The separation is successful in CPU and GPU.O modes but it fails when using Quadro P 2200. It is not finding a suitable kernel.  I am including the relevant portion of the Log file for your review below.

Also, I could not see OpenVino Music Style Remix in effects. I can see openVino Music Generation in Generators. Are they the same thing, or is something missing here?

**_The Log report of failure on GPU:_**

18:08:01: Operation 'Importing MP3 files' took 0.157000 seconds. Poll was called 2623 times and took 0.000161 seconds. Yield was called 0 times and took 0.000000 seconds.
18:08:01: Operation 'Music Information Retrieval' took 0.000000 seconds. Poll was called 0 times and took 0.000000 seconds. Yield was called 0 times and took 0.000000 seconds.
18:08:19: Operation 'Pre-processing' took 0.000000 seconds. Poll was called 0 times and took 0.000000 seconds. Yield was called 0 times and took 0.000000 seconds.
18:08:21: Error: In Music Separation, exception: Exception from src\inference\src\cpp\core.cpp:126:
Exception from src\inference\src\dev\plugin.cpp:54:
Check 'false' failed at src\plugins\intel_gpu\src\plugin\program_builder.cpp:179:
[GPU] ProgramBuilder build failed!
Exception from src\plugins\intel_gpu\src\graph\include\primitive_type_base.h:58:
[GPU] Can't choose implementation for convert:Multiply_56787 node (type=reorder)
[GPU] Original name: Multiply_56787
[GPU] Original type: Convert
[GPU] Reason: Check '!kernels.empty()' failed at src\plugins\intel_gpu\src\kernel_selector\kernel_selector.cpp:70:
[GPU] Couldn't find a suitable kernel for convert:Multiply_56787 params raw string: F16_BFYX_v1_p0_0_v1_p0_0_v2048_p0_0_v512_p0_0;F32_BFYX_v1_p0_0_v1_p0_0_v2048_p0_0_v512_p0_0

**Comment by RyanMetcalfeInt8** [comment]
Hi @umishrak,

1. For GPU failure, this is because NVidia devices are not well-supported by underlying OpenVINO framework.

2. Music Style Remix was a stable diffusion-based feature that we initially released with our v3.4.2-R1 release last year. We've since removed these features, and will be gradually replacing them with a different type of Music Generation method (MusicGen LLM). So, the current release support Music Generation (and continuation), but you won't find Music Style Remix there and we haven't replaced it yet. The closest feature to 'Music Style Remix' is the audio continuation feature (give some sample input audio + txt prompt, and it will generate a continuation) -- this is part of the Music Generation effect. Documentation is here: https://github.com/intel/openvino-plugins-ai-audacity/tree/main/doc/feature_doc/music_generation

**Comment by umishrak** [comment]
Thank you so much for all the information. This solves all my queries. In the meantime, I'll be using the CPU for openVINO projects. Thank you so much!

**Comment by gblong1** [comment]
Hi @umishrak  - The intel integrated GPU.0 should work very well for OpenVINO and will usually give better performance than CPU. Feel free to experiment and see what works best for you!

**Comment by umishrak** [comment]
Hi @gblong1. I tried all the options but for me, my CPU performed better than GPU.O
