### ISSUE TITLE
remix

### ISSUE THREAD

**Issue by mishav78** [intel/openvino-plugins-ai-audacity#234]
does this remix a song into a different genre? especially with words?

**Comment by RyanMetcalfeInt8** [comment]
Hi @mishav78,

Our latest set of plugins no longer include music style remix. We may eventually add it back in.

The original feature would 'remix' some audio snippet based on some input prompt. It was really only effective for instrumental audio snippets, and to be honest, didn't work that great in general (which is why we removed it).

**Comment by mishav78** [comment]
was it working on riffusion or Facebook small?

**Comment by RyanMetcalfeInt8** [comment]
It was working originally with riffusion. Our original gen ai features like Music Gen and Remix were based on Riffusion. And we've transitioned to meta's MusicGen LLM model for Music Generation (and continuation) feature.

**Comment by mishav78** [comment]
is there anywhere where I can hear a track or snippet that was remixed before and after?
