### ISSUE TITLE
GPU not being utilized

### ISSUE THREAD

**Issue by zeknife** [intel/openvino-plugins-ai-audacity#24]
When using music separation and selecting GPU, my GPU memory usage increases (by 2-3 GB) but the utilization stays at 0%, and I don't seem to gain any additional speed compared to selecting CPU.
Specs:
GTX 1070 8GB
Core i7-2600k

**Comment by RyanMetcalfeInt8** [comment]
Hi @zeknife,

This may be expected behavior. I don't have a similar setup to benchmark with, but using GPU through OpenVINO is typically more optimized for Intel GPUs (Either 7th Gen and later integrated graphics, Intel ARC). And I believe your CPU (2nd Gen i7) is old enough where it doesn't include an integrated GPU that OpenVINO supports.

Best Regards,
Ryan
