### ISSUE TITLE
Effect only worked once

### ISSUE THREAD

**Issue by vtrx-az** [intel/openvino-plugins-ai-audacity#25]
The installation was done correctly.
I used the effect to separate the voice and it worked perfectly, but every time I try to use it again, the result is the audio with voice and instruments and another, which would be just voice, with just noise.
I restarted the application, but nothing changed.

**Comment by RyanMetcalfeInt8** [comment]
Hi @vtrx-az,

This appears to be a duplicate of this issue: #1 

Can I ask what kind of hardware setup that you are using (CPU model), as well as version of Windows?

By the way, a workaround to this issue to remove the ```%appdata%\audacity\openvino-model-cache``` directory. It's certainly not ideal, as you'll need to delete this folder manually before each effect that you run. 

For the next release, I'll probably include a way to disable OpenVINO model caching (or even better, figure out what the issue is there).

Thanks!
Ryan

**Comment by vtrx-az** [comment]
Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz .
Windows 10 64 bits.

**Comment by mvanninhuys** [comment]
I have the same issue. This post works also for me 👍

**Comment by RyanMetcalfeInt8** [comment]
I'll close this one, as it's a duplicate of #1
