### ISSUE TITLE
Error openvino v3.7.0-R4.0

### ISSUE THREAD

**Issue by Starkad023** [intel/openvino-plugins-ai-audacity#320]
Hello, this message came up when I tried to open Audacity 3.7.0-R4.0 withy openvino music separation module. 

![error openvino](https://github.com/user-attachments/assets/f6b3c42d-4f7c-4606-9a2c-2d1cf26bb368)

Appreciate any help.

**Comment by RyanMetcalfeInt8** [comment]
Hi @Starkad023, this kind of error typically happens when you are trying to use these 64-bit plugins inside of a 32-bit installation of Audacity. Can you double check that you downloaded / installed 64-bit version of Audacity?

https://github.com/audacity/audacity/releases/download/Audacity-3.7.0/audacity-win-3.7.0-64bit.exe

**Comment by Starkad023** [comment]
You're absolutely right. 
I had a 32-bit version installed. 
It was my fault. 

That solved the problem. 

Thank you very much.

**Comment by RyanMetcalfeInt8** [comment]
You're welcome, enjoy!
