### ISSUE TITLE
converts the OpenVINO AI Plugins for Audacity plugin file to .deb

### ISSUE THREAD

**Issue by Ramirogusmao** [intel/openvino-plugins-ai-audacity#33]
Where can I find the OpenVINO AI Plug-ins for Audacity plugin files?

for i convert to .deb

**Comment by RyanMetcalfeInt8** [comment]
Hi @Ramirogusmao,

I'm sorry, I don't really understand the question -- can you give some more details?

Since you mention .deb, maybe you are trying to get it running on Linux. For this, you need to build plugins from source. The instructions are here: https://github.com/intel/openvino-plugins-ai-audacity/blob/main/doc/build_doc/linux/README.md
