### ISSUE TITLE
Open vino keeps crashing audacity when using 

### ISSUE THREAD

**Issue by dielectriclull** [intel/openvino-plugins-ai-audacity#49]
everytime i try to use vino in audacity it crashes or says 59 hrs to add effect to a 5 sec sample. then when i hit cancel the effect it crashes. if i dont hit cancel it will crash within minutes anyway. what can i do to make this not happen?

**Comment by RyanMetcalfeInt8** [comment]
Hmm, can you give some details about your hardware setup (CPU version, amount of system memory, etc.)? 

Which effect are you trying to use? Or does it happen with any of the AI effects?

**Comment by dielectriclull** [comment]
Inspiron 15 3000 Laptop

Dell
https://www.dell.com › inspiron-15-3000-laptop › spd
Processor. Intel® Pentium® N5030 (4 MB Cache, 4 Core, 4 Threads, 1.10 GHz to 3.10 GHz, 6 W) · Operating System.

36GB free

it happens with all effects

**Comment by RyanMetcalfeInt8** [comment]
Hmm, is there a crash log / debug report that pops up when it crashes?

**Comment by dielectriclull** [comment]
![Screenshot 2024-02-12 085646](https://github.com/intel/openvino-plugins-ai-audacity/assets/159724534/b562e398-aae6-427b-b080-9fbe5eaf2216)
i let it run for 20 min yesterday and i had to stop it again and then it crashes upon cancelling effect
the green bar never goes up
and it will even say rendering will take 59 hours sometimes

**Comment by RyanMetcalfeInt8** [comment]
Is the 'device' selection(s) set to CPU? Some might default to GPU. I would try first on CPU.

And just to give some insight into what's happening under the hood. When you start running one of these effects, the very first step is that it needs to compile / load the models for the device that you've selected. If it's the *very* first time running with a given effect, it might take quite a long time to compile. And during this compilation step, our plugin doesn't have a way to know how close it is to completing -- so we don't update the Audacity progress bar. So, to the user it appears that nothing is happening... 

20 mins is really long though... in general, compiling for GPU takes much longer than for CPU, so again, try that device first. Probably the 'smallest' model is noise suppression, so that would be a good one to start with as well... in terms of seeing if it actually completes.

**Comment by dielectriclull** [comment]
how do change the device selections to set to cpu? i cant figure it out on my own

**Comment by dielectriclull** [comment]
is this where i change it or is it already set ?
![Screenshot 2024-02-12 135842](https://github.com/intel/openvino-plugins-ai-audacity/assets/159724534/131eefa7-c347-4a1f-bb7c-0d1c4544a55c)

**Comment by RyanMetcalfeInt8** [comment]
Sometimes it's called 'OpenVINO inference Device'. It's a drop down box. For example, see circled part of this screenshot:

<img width="875" alt="image" src="https://github.com/intel/openvino-plugins-ai-audacity/assets/107415876/ee77b6d9-dc56-4bee-b40b-12331f12d7ce">

**Comment by RyanMetcalfeInt8** [comment]
In the screenshot you posted, on the right side there are a bunch of drop-down lists where some of them are set to 'GPU'. Start by changing those to 'CPU'.

**Comment by dielectriclull** [comment]
ok will try that. also noise suppression worked fine but it was set to cpu

**Comment by dielectriclull** [comment]
it appears to be doing something now! will report back thank you for helping me

**Comment by dielectriclull** [comment]
it works now ! how long does it take before it gets cached and doesnt take as long? a 15 sec sample takes about 4 min to remix. if i wnted to a whole song it said 45 min. will that go down or is that just how it works?

**Comment by RyanMetcalfeInt8** [comment]
The model loading will be cached after the first run. This means that the time where it says 'Model is loading' will reduce after the first run, but it will take the same amount of time to actually process.

Music Generation is the 'heaviest' model included in the current set of AI plugins. Given your system specs, I'm not too surprised that it is taking that long. So to answer your question -- this is just how it works. On systems with faster CPUs / GPUs, it would be much faster.

**Comment by RyanMetcalfeInt8** [comment]
Hi @dielectriclull,

I'm going to go ahead and close this one, as I *think* things appear to be running as expected. Feel free to re-open or file a new issue if something else pops up. Thanks!
