### ISSUE TITLE
mod-openvino

### ISSUE THREAD

**Issue by 2582-2582** [intel/openvino-plugins-ai-audacity#59]
I've downloaded the files and moved them to the places shown in the video and restarted Audacity several times.  But when I open the Effects tab there is no openvino option.  Help needed.  I want to separate a song into four stems.

Thanks - Dave W

**Comment by roughskeleton** [comment]
Did you activate the module in Audacity? To make sure, go to Edit -> Preferences -> Modules, then find mod-openvino in the list, and make sure the dropdown next to it is set to Enabled instead of New. Once you've done that and hit OK, then restart Audacity, and as long as the files and everything are in the right spots, you should be good to go.

**Comment by jumbito2** [comment]
descargue los archivos...los moví a los lugares que se te indíca y cheque en audacity pero no me aparece en el lugar de los modulos....ojala y me pudieran ayudar

**Comment by RyanMetcalfeInt8** [comment]
> descargue los archivos...los moví a los lugares que se te indíca y cheque en audacity pero no me aparece en el lugar de los modulos....ojala y me pudieran ayudar

Double check that ```mod-openvino.dll``` has been copied to ```modules``` folder (this folder is in same directory as ```Audacity.exe```).

If you don't see it, I would recommend that you re-run the installation steps (following along to the video, performing same actions step by step).

**Comment by jumbito2** [comment]
hola que tal buendia....muchas gracias si pude solucionarlo!
