### ISSUE TITLE
MOD-OPENVINO

### ISSUE THREAD

**Issue by Rosesluca** [intel/openvino-plugins-ai-audacity#61]
Tudo instalado corretamente e configurado conforme vídeo explicativo, porém ao abrir o Audacity ele me dá a seguinte menssagem:
conforme o anexo:
![Captura de Tela (52)](https://github.com/intel/openvino-plugins-ai-audacity/assets/160733948/f8f8793a-f637-474d-9fcb-ec8aaefa6cb1)

e quando entro no Audacity ele me diz que o modulo "OPENVINO " está como falhou

**Comment by RyanMetcalfeInt8** [comment]
Hi @Rosesluca,

Which version of Windows are you using, and can you share some details of your hardware setup (like CPU version, etc.)?

I have been seeing occasional reports of this DLL initialization error, and am still trying to figure out what is causing it. It's somewhat tricky for me to debug, because I can't seem to reproduce it on any of my Windows 10 / Windows 11 setups.

Thanks,
Ryan

**Comment by jevcostam** [comment]
I have exactly the same error.

Thanks.

**Comment by RyanMetcalfeInt8** [comment]
@jevcostam, could you share Windows version and CPU details?

**Comment by jevcostam** [comment]
Edition: Windows 10 Home
Version: 22H2

Intel(R) Core(TM) i5 CPU       M 430  @ 2.27GHz   2.27 GHz

**Comment by RyanMetcalfeInt8** [comment]
Hi @jevcostam,

I believe this is because your CPU does not support AVX / AVX2 instructions. The transcription library that we use, whisper.cpp, uses AVX2 instructions to speed up some computations on the CPU.

Thanks,
Ryan
